name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Space Registry
        uses: docker/login-action@v2
        with:
          registry: registry.jetbrains.team
          username: ${{ secrets.SPACE_REGISTRY_USERNAME }}
          password: ${{ secrets.SPACE_REGISTRY_PASSWORD }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🤖 Applied fixes by Qodana
          commit_user_name: Qodana Bot
          commit_user_email: bot@qodana.cloud
          commit_author: Qodana <bot@qodana.cloud>

