name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Space Registry
        uses: docker/login-action@v2
        with:
          registry: registry.jetbrains.team
          username: ${{ secrets.SPACE_REGISTRY_USERNAME }}
          password: ${{ secrets.SPACE_REGISTRY_PASSWORD }}
      - run: docker pull registry.jetbrains.team/p/sa/containers/qodana-jvm:latest
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.1.0
        with:
          args: --skip-pull
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: push
        uses: actions-x/commit@v6 
        with:
          email: bot@qodana.cloud
          name: Qodana Bot
          message: 🤖 Applied fixes by Qodana
